import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import QuestionsComponent from "@/components/questions/Questions";
import dynamic from "next/dynamic";
const ResultsComponent = dynamic(
  () => import("../components/results/Results"),
  { ssr: false }
);

export default function Home() {
  //SAMPLE QUESTION
  const getQuestion = () => {
    return {
      text: "Which biscuit is best?",
      options: [
        {
          key: "A",
          text: "Jammy Dodger",
          votes: 0,
          src: "images/jamiedodger.jpg",
        },
        { key: "B", text: "Oreo", votes: 0, src: "images/oreo.jpg" },
        { key: "C", text: "Bourbon", votes: 0, src: "images/bourbon.jpg" },
        {
          key: "D",
          text: "Custard cream",
          votes: 0,
          src: "images/custardcream.jpg",
        },
      ],
    };
  };

  const question = getQuestion();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <header className={styles.header}>
          <img
            src="/images/smsvote.svg"
            alt="sms vote"
            className={styles.logo}
          />
          <h1 className={styles.title}>
            Text: (+33) 644 63 42 09
            <br />
            to vote
          </h1>
        </header>
        <QuestionsComponent question={question} />
        <ResultsComponent question={question} />
      </main>
    </div>
  );
}
